### ISSUE TITLE
IllegalStateException when RPickMedia.pickFromCamera called.

### ISSUE THREAD

**Issue by zeallat** [WindSekirun/RichUtilsKt#13]
`07-21 18:32:02.659 22345-22458/com.appg.navion W/ExifInterface: Skip the tag entry since tag number is not defined: 2
07-21 18:32:03.395 22345-22345/com.appg.navion D/AndroidRuntime: Shutting down VM
07-21 18:32:03.402 22345-22345/com.appg.navion E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.appg.navion, PID: 22345
                                                                 java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                     at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1434)
                                                                     at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1452)
                                                                     at android.app.BackStackRecord.commitInternal(BackStackRecord.java:708)
                                                                     at android.app.BackStackRecord.commit(BackStackRecord.java:672)
                                                                     at pyxis.uzuki.live.richutilskt.utils.RPickMedia.requestPhotoPick(RPickMedia.kt:78)
                                                                     at pyxis.uzuki.live.richutilskt.utils.RPickMedia.pickFromGallery(RPickMedia.kt:51)
                                                                     at com.appg.navion.myhome.photo.edit.MyHomePhotoEditActivity.onTakePhotoClicked(MyHomePhotoEditActivity.java:67)
                                                                     at com.appg.navion.myhome.photo.edit.MyHomePhotoEditActivity_ViewBinding$1.doClick(MyHomePhotoEditActivity_ViewBinding.java:37)
                                                                     at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                     at android.view.View.performClick(View.java:5637)
                                                                     at android.view.View$PerformClick.run(View.java:22429)
                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
`

IllegalStateException when RPickMedia.pickFromCamera called in activity that has cropImageView.

아몰랑 고쳐줘요

**Comment by WindSekirun** [comment]
This issue will fix in 1.3.0.1

**Comment by WindSekirun** [comment]
Released!
