### ISSUE TITLE
Oreo 8.0: ResultFragment must be a public static class 

### ISSUE THREAD

**Issue by WindSekirun** [WindSekirun/RichUtilsKt#31]
```
  Caused by: java.lang.IllegalStateException: Fragment pyxis.uzuki.live.richutilskt.utils.RPickMedia.ResultFragment must be a public static class to be  properly recreated from instance state.
                      at android.app.BackStackRecord.doAddOp(BackStackRecord.java:429)
                      at android.app.BackStackRecord.add(BackStackRecord.java:409)
                      at pyxis.uzuki.live.richutilskt.utils.RPickMedia.requestPhotoPick(RPickMedia.kt:119)
                      at pyxis.uzuki.live.richutilskt.utils.RPickMedia.pickFromGallery(RPickMedia.kt:80)
                      at android.app.Activity.performCreate(Activity.java:7173)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2889)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3011) 
                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6888) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1370) 
```

**Comment by WindSekirun** [comment]
Fix in 1.8.0-fragment-SNAPSHOT

Jitpack is ```'com.github.WindSekirun:RichUtilsKt:1.8.0-fragment-SNAPSHOT'```
